from __future__ import annotations

from typing import Dict, List

from preset_system.preset_schema import PresetConfig

# 20+ örnek preset JSON tanımı; her biri Graph JSON patch formatını içerir.
# Patch'ler demo amaçlı kısa süreler kullanır; gerçek projede süre ve parametreleri özelleştirebilirsiniz.

PRESET_DEFINITIONS: List[Dict] = [
    {
        "id": "warm_sine_pad",
        "name": "Warm Sine Pad",
        "tags": ["warm", "pad", "sine", "slow", "soft"],
        "target_use": "sleep",
        "duration_hint": 8.0,
        "graph": {
            "sample_rate": 44_100,
            "global_params": {"duration": 8.0},
            "nodes": [
                {"name": "osc_low", "type": "oscillator", "params": {"waveform": "sine", "frequency": 220.0, "amplitude": 0.35}},
                {"name": "osc_high", "type": "oscillator", "params": {"waveform": "triangle", "frequency": 330.0, "amplitude": 0.25}},
                {"name": "mix", "type": "mix"},
                {"name": "env", "type": "envelope", "params": {"attack": 0.6, "decay": 1.2, "sustain": 0.85, "release": 2.2}},
                {"name": "filter", "type": "filter", "params": {"type": "lowpass", "cutoff": 1_800.0}},
                {"name": "pan", "type": "pan", "params": {"pan": 0.0}},
                {"name": "out", "type": "output"},
            ],
            "edges": [
                {"source": "osc_low", "target": "mix"},
                {"source": "osc_high", "target": "mix"},
                {"source": "mix", "target": "env"},
                {"source": "env", "target": "filter"},
                {"source": "filter", "target": "pan"},
                {"source": "pan", "target": "out"},
            ],
        },
    },
    {
        "id": "rain_plush",
        "name": "Plush Rain",
        "tags": ["rain", "noise", "soft", "calm", "pink"],
        "target_use": "sleep",
        "duration_hint": 10.0,
        "graph": {
            "sample_rate": 44_100,
            "global_params": {"duration": 10.0},
            "nodes": [
                {"name": "bed", "type": "noise", "params": {"type": "pink", "amplitude": 0.5}},
                {"name": "filter", "type": "filter", "params": {"type": "bandpass", "low_cutoff": 120.0, "high_cutoff": 9_500.0}},
                {"name": "pan", "type": "pan", "params": {"pan": -0.15}},
                {"name": "out", "type": "output"},
            ],
            "edges": [
                {"source": "bed", "target": "filter"},
                {"source": "filter", "target": "pan"},
                {"source": "pan", "target": "out"},
            ],
        },
    },
    {
        "id": "brown_sub_sleep",
        "name": "Brown Sub Sleep",
        "tags": ["brown", "noise", "low", "warm", "sleep"],
        "target_use": "sleep",
        "duration_hint": 12.0,
        "graph": {
            "sample_rate": 44_100,
            "global_params": {"duration": 12.0},
            "nodes": [
                {"name": "bed", "type": "noise", "params": {"type": "brown", "amplitude": 0.7}},
                {"name": "filter", "type": "filter", "params": {"type": "lowpass", "cutoff": 320.0}},
                {"name": "gain", "type": "gain", "params": {"gain_db": -6.0}},
                {"name": "out", "type": "output"},
            ],
            "edges": [
                {"source": "bed", "target": "filter"},
                {"source": "filter", "target": "gain"},
                {"source": "gain", "target": "out"},
            ],
        },
    },
    {
        "id": "airy_focus_noise",
        "name": "Airy Focus Noise",
        "tags": ["bright", "airy", "focus", "noise", "pink"],
        "target_use": "focus",
        "duration_hint": 5.0,
        "graph": {
            "sample_rate": 44_100,
            "global_params": {"duration": 5.0},
            "nodes": [
                {"name": "bed", "type": "noise", "params": {"type": "pink", "amplitude": 0.3}},
                {"name": "filter", "type": "filter", "params": {"type": "highpass", "cutoff": 2_400.0}},
                {"name": "pan", "type": "pan", "params": {"pan": 0.05}},
                {"name": "out", "type": "output"},
            ],
            "edges": [
                {"source": "bed", "target": "filter"},
                {"source": "filter", "target": "pan"},
                {"source": "pan", "target": "out"},
            ],
        },
    },
    {
        "id": "binaural_theta",
        "name": "Binaural Theta Drift",
        "tags": ["binaural", "theta", "calm", "stereo", "meditation"],
        "target_use": "meditation",
        "duration_hint": 6.0,
        "graph": {
            "sample_rate": 44_100,
            "global_params": {"duration": 6.0},
            "nodes": [
                {"name": "osc_l", "type": "oscillator", "params": {"waveform": "sine", "frequency": 128.0, "amplitude": 0.22}},
                {"name": "env_l", "type": "envelope", "params": {"attack": 0.2, "decay": 0.6, "sustain": 0.8, "release": 0.8}},
                {"name": "pan_l", "type": "pan", "params": {"pan": -0.6}},
                {"name": "osc_r", "type": "oscillator", "params": {"waveform": "sine", "frequency": 134.0, "amplitude": 0.22}},
                {"name": "env_r", "type": "envelope", "params": {"attack": 0.2, "decay": 0.6, "sustain": 0.8, "release": 0.8}},
                {"name": "pan_r", "type": "pan", "params": {"pan": 0.6}},
                {"name": "mix", "type": "mix"},
                {"name": "out", "type": "output"},
            ],
            "edges": [
                {"source": "osc_l", "target": "env_l"},
                {"source": "env_l", "target": "pan_l"},
                {"source": "osc_r", "target": "env_r"},
                {"source": "env_r", "target": "pan_r"},
                {"source": "pan_l", "target": "mix"},
                {"source": "pan_r", "target": "mix"},
                {"source": "mix", "target": "out"},
            ],
        },
    },
    {
        "id": "alpha_focus_beats",
        "name": "Alpha Focus Beats",
        "tags": ["alpha", "focus", "binaural", "clean", "tone"],
        "target_use": "focus",
        "duration_hint": 5.5,
        "graph": {
            "sample_rate": 44_100,
            "global_params": {"duration": 5.5},
            "nodes": [
                {"name": "osc_a", "type": "oscillator", "params": {"waveform": "sine", "frequency": 210.0, "amplitude": 0.2}},
                {"name": "env_a", "type": "envelope", "params": {"attack": 0.15, "decay": 0.4, "sustain": 0.75, "release": 0.6}},
                {"name": "pan_a", "type": "pan", "params": {"pan": -0.4}},
                {"name": "osc_b", "type": "oscillator", "params": {"waveform": "sine", "frequency": 220.0, "amplitude": 0.2}},
                {"name": "env_b", "type": "envelope", "params": {"attack": 0.15, "decay": 0.4, "sustain": 0.75, "release": 0.6}},
                {"name": "pan_b", "type": "pan", "params": {"pan": 0.4}},
                {"name": "hiss", "type": "noise", "params": {"type": "white", "amplitude": 0.08}},
                {"name": "hiss_filter", "type": "filter", "params": {"type": "highpass", "cutoff": 1_200.0}},
                {"name": "hiss_gain", "type": "gain", "params": {"gain_db": -2.0}},
                {"name": "mix", "type": "mix"},
                {"name": "out", "type": "output"},
            ],
            "edges": [
                {"source": "osc_a", "target": "env_a"},
                {"source": "env_a", "target": "pan_a"},
                {"source": "osc_b", "target": "env_b"},
                {"source": "env_b", "target": "pan_b"},
                {"source": "pan_a", "target": "mix"},
                {"source": "pan_b", "target": "mix"},
                {"source": "hiss", "target": "hiss_filter"},
                {"source": "hiss_filter", "target": "hiss_gain"},
                {"source": "hiss_gain", "target": "mix"},
                {"source": "mix", "target": "out"},
            ],
        },
    },
    {
        "id": "slow_saw_pad",
        "name": "Slow Saw Pad",
        "tags": ["saw", "pad", "warm", "ambient", "slow"],
        "target_use": "ambient",
        "duration_hint": 9.0,
        "graph": {
            "sample_rate": 44_100,
            "global_params": {"duration": 9.0},
            "nodes": [
                {"name": "osc_saw", "type": "oscillator", "params": {"waveform": "saw", "frequency": 110.0, "amplitude": 0.35}},
                {"name": "osc_sub", "type": "oscillator", "params": {"waveform": "sine", "frequency": 55.0, "amplitude": 0.18}},
                {"name": "mix", "type": "mix"},
                {"name": "env", "type": "envelope", "params": {"attack": 1.0, "decay": 1.0, "sustain": 0.85, "release": 2.0}},
                {"name": "filter", "type": "filter", "params": {"type": "lowpass", "cutoff": 1_200.0}},
                {"name": "pan", "type": "pan", "params": {"pan": -0.05}},
                {"name": "out", "type": "output"},
            ],
            "edges": [
                {"source": "osc_saw", "target": "mix"},
                {"source": "osc_sub", "target": "mix"},
                {"source": "mix", "target": "env"},
                {"source": "env", "target": "filter"},
                {"source": "filter", "target": "pan"},
                {"source": "pan", "target": "out"},
            ],
        },
    },
    {
        "id": "shimmer_triangle",
        "name": "Shimmer Triangle",
        "tags": ["triangle", "bright", "focus", "shimmer", "light"],
        "target_use": "focus",
        "duration_hint": 6.0,
        "graph": {
            "sample_rate": 44_100,
            "global_params": {"duration": 6.0},
            "nodes": [
                {"name": "osc_main", "type": "oscillator", "params": {"waveform": "triangle", "frequency": 440.0, "amplitude": 0.28}},
                {"name": "osc_air", "type": "oscillator", "params": {"waveform": "sine", "frequency": 880.0, "amplitude": 0.12}},
                {"name": "mix", "type": "mix"},
                {"name": "env", "type": "envelope", "params": {"attack": 0.1, "decay": 0.2, "sustain": 0.7, "release": 0.6}},
                {"name": "filter", "type": "filter", "params": {"type": "lowpass", "cutoff": 3_500.0}},
                {"name": "pan", "type": "pan", "params": {"pan": 0.1}},
                {"name": "out", "type": "output"},
            ],
            "edges": [
                {"source": "osc_main", "target": "mix"},
                {"source": "osc_air", "target": "mix"},
                {"source": "mix", "target": "env"},
                {"source": "env", "target": "filter"},
                {"source": "filter", "target": "pan"},
                {"source": "pan", "target": "out"},
            ],
        },
    },
    {
        "id": "ocean_swells",
        "name": "Ocean Swells",
        "tags": ["ocean", "brown", "movement", "calm", "sleep"],
        "target_use": "sleep",
        "duration_hint": 10.0,
        "graph": {
            "sample_rate": 44_100,
            "global_params": {"duration": 10.0},
            "nodes": [
                {"name": "bed", "type": "noise", "params": {"type": "brown", "amplitude": 0.6}},
                {"name": "filter", "type": "filter", "params": {"type": "bandpass", "low_cutoff": 70.0, "high_cutoff": 4_200.0}},
                {"name": "env", "type": "envelope", "params": {"attack": 0.4, "decay": 0.6, "sustain": 0.9, "release": 1.0}},
                {"name": "pan", "type": "pan", "params": {"pan": -0.05}},
                {"name": "out", "type": "output"},
            ],
            "edges": [
                {"source": "bed", "target": "filter"},
                {"source": "filter", "target": "env"},
                {"source": "env", "target": "pan"},
                {"source": "pan", "target": "out"},
            ],
        },
    },
    {
        "id": "fire_crackle",
        "name": "Fire Crackle",
        "tags": ["fire", "asmr", "crackle", "warm", "bright"],
        "target_use": "asmr",
        "duration_hint": 5.0,
        "graph": {
            "sample_rate": 44_100,
            "global_params": {"duration": 5.0},
            "nodes": [
                {"name": "bed", "type": "noise", "params": {"type": "white", "amplitude": 0.3}},
                {"name": "filter", "type": "filter", "params": {"type": "highpass", "cutoff": 3_500.0}},
                {"name": "gain", "type": "gain", "params": {"gain_db": -4.0}},
                {"name": "pan", "type": "pan", "params": {"pan": -0.15}},
                {"name": "out", "type": "output"},
            ],
            "edges": [
                {"source": "bed", "target": "filter"},
                {"source": "filter", "target": "gain"},
                {"source": "gain", "target": "pan"},
                {"source": "pan", "target": "out"},
            ],
        },
    },
    {
        "id": "wind_whisper",
        "name": "Wind Whisper",
        "tags": ["wind", "soft", "focus", "noise", "airy"],
        "target_use": "focus",
        "duration_hint": 7.0,
        "graph": {
            "sample_rate": 44_100,
            "global_params": {"duration": 7.0},
            "nodes": [
                {"name": "bed", "type": "noise", "params": {"type": "white", "amplitude": 0.35}},
                {"name": "filter", "type": "filter", "params": {"type": "bandpass", "low_cutoff": 200.0, "high_cutoff": 9_500.0}},
                {"name": "env", "type": "envelope", "params": {"attack": 0.25, "decay": 0.4, "sustain": 0.85, "release": 0.5}},
                {"name": "pan", "type": "pan", "params": {"pan": 0.2}},
                {"name": "out", "type": "output"},
            ],
            "edges": [
                {"source": "bed", "target": "filter"},
                {"source": "filter", "target": "env"},
                {"source": "env", "target": "pan"},
                {"source": "pan", "target": "out"},
            ],
        },
    },
    {
        "id": "space_choir",
        "name": "Space Choir",
        "tags": ["space", "pad", "choral", "soft", "ambient"],
        "target_use": "meditation",
        "duration_hint": 8.0,
        "graph": {
            "sample_rate": 44_100,
            "global_params": {"duration": 8.0},
            "nodes": [
                {"name": "osc_main", "type": "oscillator", "params": {"waveform": "sine", "frequency": 320.0, "amplitude": 0.2}},
                {"name": "osc_harm", "type": "oscillator", "params": {"waveform": "saw", "frequency": 480.0, "amplitude": 0.16}},
                {"name": "mix", "type": "mix"},
                {"name": "filter", "type": "filter", "params": {"type": "lowpass", "cutoff": 2_600.0}},
                {"name": "env", "type": "envelope", "params": {"attack": 0.7, "decay": 0.8, "sustain": 0.75, "release": 1.5}},
                {"name": "pan", "type": "pan", "params": {"pan": 0.0}},
                {"name": "out", "type": "output"},
            ],
            "edges": [
                {"source": "osc_main", "target": "mix"},
                {"source": "osc_harm", "target": "mix"},
                {"source": "mix", "target": "filter"},
                {"source": "filter", "target": "env"},
                {"source": "env", "target": "pan"},
                {"source": "pan", "target": "out"},
            ],
        },
    },
    {
        "id": "forest_rustle",
        "name": "Forest Rustle",
        "tags": ["forest", "ambience", "rustle", "pink", "ambient"],
        "target_use": "ambient",
        "duration_hint": 9.0,
        "graph": {
            "sample_rate": 44_100,
            "global_params": {"duration": 9.0},
            "nodes": [
                {"name": "bed", "type": "noise", "params": {"type": "pink", "amplitude": 0.42}},
                {"name": "filter", "type": "filter", "params": {"type": "bandpass", "low_cutoff": 180.0, "high_cutoff": 8_200.0}},
                {"name": "gain", "type": "gain", "params": {"gain_db": -3.0}},
                {"name": "pan", "type": "pan", "params": {"pan": -0.2}},
                {"name": "out", "type": "output"},
            ],
            "edges": [
                {"source": "bed", "target": "filter"},
                {"source": "filter", "target": "gain"},
                {"source": "gain", "target": "pan"},
                {"source": "pan", "target": "out"},
            ],
        },
    },
    {
        "id": "sunrise_chords",
        "name": "Sunrise Chords",
        "tags": ["warm", "triad", "soft", "ambient", "pad"],
        "target_use": "ambient",
        "duration_hint": 6.0,
        "graph": {
            "sample_rate": 44_100,
            "global_params": {"duration": 6.0},
            "nodes": [
                {"name": "osc_c", "type": "oscillator", "params": {"waveform": "sine", "frequency": 261.63, "amplitude": 0.25}},
                {"name": "osc_e", "type": "oscillator", "params": {"waveform": "sine", "frequency": 329.63, "amplitude": 0.2}},
                {"name": "osc_g", "type": "oscillator", "params": {"waveform": "sine", "frequency": 392.0, "amplitude": 0.18}},
                {"name": "mix", "type": "mix"},
                {"name": "env", "type": "envelope", "params": {"attack": 0.4, "decay": 0.8, "sustain": 0.88, "release": 1.0}},
                {"name": "filter", "type": "filter", "params": {"type": "lowpass", "cutoff": 2_400.0}},
                {"name": "pan", "type": "pan", "params": {"pan": 0.05}},
                {"name": "out", "type": "output"},
            ],
            "edges": [
                {"source": "osc_c", "target": "mix"},
                {"source": "osc_e", "target": "mix"},
                {"source": "osc_g", "target": "mix"},
                {"source": "mix", "target": "env"},
                {"source": "env", "target": "filter"},
                {"source": "filter", "target": "pan"},
                {"source": "pan", "target": "out"},
            ],
        },
    },
    {
        "id": "low_sub_breath",
        "name": "Low Sub Breath",
        "tags": ["sub", "breath", "calm", "sleep", "low"],
        "target_use": "meditation",
        "duration_hint": 10.0,
        "graph": {
            "sample_rate": 44_100,
            "global_params": {"duration": 10.0},
            "nodes": [
                {"name": "osc_sub", "type": "oscillator", "params": {"waveform": "sine", "frequency": 50.0, "amplitude": 0.4}},
                {"name": "env", "type": "envelope", "params": {"attack": 0.8, "decay": 0.6, "sustain": 0.7, "release": 1.5}},
                {"name": "filter", "type": "filter", "params": {"type": "lowpass", "cutoff": 400.0}},
                {"name": "pan", "type": "pan", "params": {"pan": 0.0}},
                {"name": "out", "type": "output"},
            ],
            "edges": [
                {"source": "osc_sub", "target": "env"},
                {"source": "env", "target": "filter"},
                {"source": "filter", "target": "pan"},
                {"source": "pan", "target": "out"},
            ],
        },
    },
    {
        "id": "crystal_meditation",
        "name": "Crystal Meditation",
        "tags": ["crystal", "bright", "triangle", "meditation", "air"],
        "target_use": "meditation",
        "duration_hint": 7.0,
        "graph": {
            "sample_rate": 44_100,
            "global_params": {"duration": 7.0},
            "nodes": [
                {"name": "osc_a", "type": "oscillator", "params": {"waveform": "sine", "frequency": 660.0, "amplitude": 0.18}},
                {"name": "osc_b", "type": "oscillator", "params": {"waveform": "triangle", "frequency": 990.0, "amplitude": 0.12}},
                {"name": "mix", "type": "mix"},
                {"name": "filter", "type": "filter", "params": {"type": "highpass", "cutoff": 500.0}},
                {"name": "env", "type": "envelope", "params": {"attack": 0.2, "decay": 0.5, "sustain": 0.75, "release": 0.8}},
                {"name": "pan", "type": "pan", "params": {"pan": 0.25}},
                {"name": "out", "type": "output"},
            ],
            "edges": [
                {"source": "osc_a", "target": "mix"},
                {"source": "osc_b", "target": "mix"},
                {"source": "mix", "target": "filter"},
                {"source": "filter", "target": "env"},
                {"source": "env", "target": "pan"},
                {"source": "pan", "target": "out"},
            ],
        },
    },
    {
        "id": "urban_air_conditioner",
        "name": "Urban Air Conditioner",
        "tags": ["urban", "hum", "focus", "noise", "steady"],
        "target_use": "ambient",
        "duration_hint": 8.0,
        "graph": {
            "sample_rate": 44_100,
            "global_params": {"duration": 8.0},
            "nodes": [
                {"name": "bed", "type": "noise", "params": {"type": "white", "amplitude": 0.3}},
                {"name": "filter", "type": "filter", "params": {"type": "bandpass", "low_cutoff": 90.0, "high_cutoff": 3_500.0}},
                {"name": "gain", "type": "gain", "params": {"gain_db": -2.0}},
                {"name": "pan", "type": "pan", "params": {"pan": -0.05}},
                {"name": "out", "type": "output"},
            ],
            "edges": [
                {"source": "bed", "target": "filter"},
                {"source": "filter", "target": "gain"},
                {"source": "gain", "target": "pan"},
                {"source": "pan", "target": "out"},
            ],
        },
    },
    {
        "id": "pink_lullaby",
        "name": "Pink Lullaby",
        "tags": ["pink", "lullaby", "soft", "sleep", "noise"],
        "target_use": "sleep",
        "duration_hint": 12.0,
        "graph": {
            "sample_rate": 44_100,
            "global_params": {"duration": 12.0},
            "nodes": [
                {"name": "bed", "type": "noise", "params": {"type": "pink", "amplitude": 0.35}},
                {"name": "filter", "type": "filter", "params": {"type": "lowpass", "cutoff": 1_800.0}},
                {"name": "gain", "type": "gain", "params": {"gain_db": -4.0}},
                {"name": "pan", "type": "pan", "params": {"pan": 0.0}},
                {"name": "out", "type": "output"},
            ],
            "edges": [
                {"source": "bed", "target": "filter"},
                {"source": "filter", "target": "gain"},
                {"source": "gain", "target": "pan"},
                {"source": "pan", "target": "out"},
            ],
        },
    },
    {
        "id": "space_glimmer",
        "name": "Space Glimmer",
        "tags": ["space", "pad", "shimmer", "ambient", "wide"],
        "target_use": "ambient",
        "duration_hint": 9.0,
        "graph": {
            "sample_rate": 44_100,
            "global_params": {"duration": 9.0},
            "nodes": [
                {"name": "osc_a", "type": "oscillator", "params": {"waveform": "saw", "frequency": 140.0, "amplitude": 0.22}},
                {"name": "osc_b", "type": "oscillator", "params": {"waveform": "sine", "frequency": 280.0, "amplitude": 0.15}},
                {"name": "osc_c", "type": "oscillator", "params": {"waveform": "sine", "frequency": 420.0, "amplitude": 0.1}},
                {"name": "mix", "type": "mix"},
                {"name": "filter", "type": "filter", "params": {"type": "bandpass", "low_cutoff": 120.0, "high_cutoff": 3_600.0}},
                {"name": "env", "type": "envelope", "params": {"attack": 0.6, "decay": 0.8, "sustain": 0.82, "release": 1.4}},
                {"name": "pan", "type": "pan", "params": {"pan": -0.1}},
                {"name": "out", "type": "output"},
            ],
            "edges": [
                {"source": "osc_a", "target": "mix"},
                {"source": "osc_b", "target": "mix"},
                {"source": "osc_c", "target": "mix"},
                {"source": "mix", "target": "filter"},
                {"source": "filter", "target": "env"},
                {"source": "env", "target": "pan"},
                {"source": "pan", "target": "out"},
            ],
        },
    },
    {
        "id": "sub_pulse",
        "name": "Sub Pulse",
        "tags": ["pulse", "low", "focus", "minimal", "bass"],
        "target_use": "focus",
        "duration_hint": 6.0,
        "graph": {
            "sample_rate": 44_100,
            "global_params": {"duration": 6.0},
            "nodes": [
                {"name": "osc", "type": "oscillator", "params": {"waveform": "sine", "frequency": 90.0, "amplitude": 0.32}},
                {"name": "env", "type": "envelope", "params": {"attack": 0.05, "decay": 0.2, "sustain": 0.6, "release": 0.4}},
                {"name": "pan", "type": "pan", "params": {"pan": 0.0}},
                {"name": "out", "type": "output"},
            ],
            "edges": [
                {"source": "osc", "target": "env"},
                {"source": "env", "target": "pan"},
                {"source": "pan", "target": "out"},
            ],
        },
    },
    {
        "id": "lofi_rain",
        "name": "Lo-Fi Rain",
        "tags": ["rain", "lofi", "noise", "warm", "sleep"],
        "target_use": "sleep",
        "duration_hint": 9.0,
        "graph": {
            "sample_rate": 44_100,
            "global_params": {"duration": 9.0},
            "nodes": [
                {"name": "bed_low", "type": "noise", "params": {"type": "brown", "amplitude": 0.28}},
                {"name": "bed_low_filt", "type": "filter", "params": {"type": "lowpass", "cutoff": 1_200.0}},
                {"name": "bed_low_pan", "type": "pan", "params": {"pan": -0.1}},
                {"name": "bed_high", "type": "noise", "params": {"type": "white", "amplitude": 0.12}},
                {"name": "bed_high_filt", "type": "filter", "params": {"type": "highpass", "cutoff": 4_000.0}},
                {"name": "bed_high_pan", "type": "pan", "params": {"pan": 0.2}},
                {"name": "mix", "type": "mix"},
                {"name": "gain", "type": "gain", "params": {"gain_db": -5.0}},
                {"name": "out", "type": "output"},
            ],
            "edges": [
                {"source": "bed_low", "target": "bed_low_filt"},
                {"source": "bed_low_filt", "target": "bed_low_pan"},
                {"source": "bed_low_pan", "target": "mix"},
                {"source": "bed_high", "target": "bed_high_filt"},
                {"source": "bed_high_filt", "target": "bed_high_pan"},
                {"source": "bed_high_pan", "target": "mix"},
                {"source": "mix", "target": "gain"},
                {"source": "gain", "target": "out"},
            ],
        },
    },
]


def load_presets() -> List[PresetConfig]:
    """Preset tanımlarını PresetConfig dataclass'ına dönüştürür."""
    return [
        PresetConfig(
            id=cfg["id"],
            name=cfg["name"],
            tags=cfg.get("tags", []),
            target_use=cfg.get("target_use"),
            duration_hint=cfg.get("duration_hint"),
            graph_patch=cfg.get("graph", {}),
        )
        for cfg in PRESET_DEFINITIONS
    ]


PRESETS: List[PresetConfig] = load_presets()
PRESET_MAP: Dict[str, PresetConfig] = {p.id: p for p in PRESETS}


__all__ = ["PRESET_DEFINITIONS", "PRESETS", "PRESET_MAP", "load_presets"]
